services:
  db:
    image: postgres:15
    container_name: produtores-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - net

  api:
    container_name: produtores-api
    build: .
    env_file:
      - .env
    ports:
      - "${PORT:-3000}:3000"
    depends_on:
      - db
    networks:
      - net

  docs:
    container_name: produtores-docs
    image: node:20
    working_dir: /app
    volumes:
      - .:/app
    command: sh -c "npm install -g @compodoc/compodoc && compodoc -p tsconfig.json -s -n 'Produtores API Docs' -w"
    ports:
      - "8080:8080"
    networks:
      - net

volumes:
  pgdata:

networks:
  net:
