version: '3.9'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  api:
    build: .
    depends_on:
      - db
    ports:
      - '3000:3000'
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_USER: postgres
      DATABASE_PASSWORD: password
      DATABASE_NAME: postgres

  docs:
    build:
      context: .
      dockerfile: Dockerfile.compodoc
    ports:
      - '8080:8080'

volumes:
  db_data:
